base: core18
name: getenv
version: '0.1-3'
summary: Keep track of your .env files
description: |
    Copies your .env files from a *synced_location* you provide to the *current
    working dir*. You can also copy all the .env files in your working
    directory to the source directory.

    If you work on different clients this is a handy tool which let you
    get your env files from a separate synced location.

    https://github.com/izznogooood/getenv
grade: stable
confinement: strict

apps:
  getenv:
    command: getenv
    plugs: [home]

parts:
  getenv:
    source: https://github.com/izznogooood/getenv.git
    source-tag: master
    plugin: python

