base: core18
name: getenv
version: '0.3.0'
summary: Keep track of your .env files
description: |
    Copies your .env files from a *source_dir* you provide (once) to the *current
    working dir*. You can also copy all the .env files in your working
    directory to the source directory.

    If you work on different clients this is a handy tool which let you
    get your env files from a separate synced location.

    Getenv has a --request option which lets you send feedback/requests 
    straight to the developer. Please use it!

    https://github.com/izznogooood/getenv
grade: stable
confinement: strict

apps:
  getenv:
    command: getenv
    plugs: [home, network]

parts:
  getenv:
    source: .
    source-tag: master
    plugin: python

