base: core18
name: getenv
version: '0.1-3'
summary: Keep track of your .env files
description: |
    Copies your .env files from a *source dir* you provide to the *current
    working dir*. You can also copy all the .env files in your working
    directory to the source directory.

    If you work on different clients this is a handy tool which let you
    keep your env files separate from your repositories.
grade: stable
confinement: devmode

plugs:
  write-home:
    interface: personal-files
    write:
    - $HOME

apps:
  getenv:
    command: getenv
    plugs:
      - write-home

parts:
  getenv:
    source: https://github.com/izznogooood/getenv.git
    source-tag: master
    plugin: python

